import React from "react";

const Home: React.FC = () => (
  <div className="p-8 space-y-8 rounded-xl shadow-lg mt-20">

    {/* ==================== Closure Properties of CFLs ==================== */}
    <h1 className="text-4xl font-extrabold border-b-2 pb-2">
      Closure Properties of Context Free Languages
    </h1>

    <p className="text-sm text-gray-500">Last Updated : 23 Jul, 2025</p>

    <p className="text-lg leading-relaxed">
      Context-Free Languages (CFLs) are generated by Context-Free Grammars (CFGs) 
      and recognized by Pushdown Automata (PDAs). Understanding closure properties 
      helps determine which operations preserve the context-free nature of a language.
    </p>

    <p className="leading-relaxed">
      CFLs are closed under some operations, but not under others. 
      A CFG has productions of the form:
    </p>

    <p className="bg-gray-400 text-sm p-4 rounded-lg shadow-inner">
      A → α &nbsp; where A ∈ N and α ∈ (T ∪ N)*
    </p>

    <h2 className="text-3xl font-bold mt-8">Properties of Context-Free Languages</h2>

    {/* ==================== 1. Union ==================== */}
    <h3 className="text-2xl font-bold mt-6">1. Union</h3>
    <p>
      If L and M are CFLs, then their union L ∪ M is also a CFL.
    </p>

    <p>
      <strong>Construction:</strong><br />
      - Let G and H be grammars for L and M with start symbols S₁ and S₂.<br />
      - Ensure no common variables.<br />
      - Add new start symbol S with production: S → S₁ | S₂.
    </p>

    <p className="leading-relaxed">
      <strong>Example:</strong> L₁ = &#123;aⁿbⁿcᵐ | n ≥ 0, m ≥ 0&#125;<br />
      L₂ = &#123;aⁿbᵐcᵐ | n ≥ 0, m ≥ 0&#125;
    </p>

    <p>
      L₁ enforces a=b, L₂ enforces b=c. Their union satisfies ≥1 of these 
      conditions → CFL.
    </p>

    {/* ==================== 2. Concatenation ==================== */}
    <h3 className="text-2xl font-bold mt-6">2. Concatenation</h3>
    <p>
      If L and M are CFLs, LM is also a CFL.
    </p>

    <p>
      <strong>Construction:</strong> S → S₁ S₂
    </p>

    <p className="leading-relaxed">
      <strong>Example:</strong><br />
      L₁ = &#123;aⁿbⁿ&#125;<br />
      L₂ = &#123;cᵐdᵐ&#125;<br />
      LM = &#123;aⁿbⁿcᵐdᵐ&#125; → CFL
    </p>

    <p>
      PDA pushes for a’s, pops for b’s, then pushes for c’s, pops for d’s.
    </p>

    {/* ==================== 3. Kleene Star ==================== */}
    <h3 className="text-2xl font-bold mt-6">3. Kleene Closure</h3>
    <p>
      If L is a CFL, then L* is also a CFL.
    </p>

    <p>
      <strong>Construction:</strong> S → S₁ S | ε
    </p>

    <p>
      Example: L = &#123;aⁿbⁿ&#125; → L* is CFL.
    </p>

    {/* ==================== 4. Intersection and Complementation ==================== */}
    <h3 className="text-2xl font-bold mt-6">4. Intersection & Complementation (Not Closed)</h3>

    <p>
      CFLs are <strong>not closed</strong> under intersection and complementation.
    </p>

    <p className="leading-relaxed">
      <strong>Example:</strong><br />
      L₁ = &#123;aⁿbⁿcᵐ&#125;<br />
      L₂ = &#123;aᵐbⁿcⁿ&#125;<br />
      L₁ ∩ L₂ = &#123;aⁿbⁿcⁿ&#125; → Not CFL.
    </p>

    <p>
      PDA cannot compare all three symbols simultaneously.
    </p>

    {/* ==================== 5. Reversal ==================== */}
    <h3 className="text-2xl font-bold mt-6">5. Reversal</h3>
    <p>
      CFLs are closed under reversal.
    </p>

    <p>
      Reverse every RHS of each production.
    </p>

    <p>Example:<br />
      S → 0S1 | 01 becomes S → 1S0 | 10
    </p>

    {/* ==================== 6. Homomorphism ==================== */}
    <h3 className="text-2xl font-bold mt-6">6. Homomorphism</h3>
    <p>
      CFLs are closed under homomorphism.
    </p>

    <p className="leading-relaxed">
      Example:<br />
      h(0)=ab, h(1)=ε
    </p>

    {/* ==================== 7. Inverse Homomorphism ==================== */}
    <h3 className="text-2xl font-bold mt-6">7. Inverse Homomorphism</h3>
    <p>
      CFLs are closed under inverse homomorphism using PDA construction.
    </p>

    {/* ==================== Deterministic CFLs ==================== */}
    <h2 className="text-3xl font-bold mt-8">Deterministic Context-Free Languages</h2>
    <p>
      DCFL ⊂ CFL. Accepted by deterministic PDA (DPDA).
    </p>

    <p className="leading-relaxed">
      DCFLs are closed under:<br />
      ✔ Complement<br />
      ✔ Inverse Homomorphism<br />
      ✖ Not closed under union/intersection
    </p>

    {/* ==================== MCQs ==================== */}
    <h2 className="text-3xl font-bold mt-8">Multiple-Choice Questions</h2>

    {/* MCQ 1 */}
    <h3 className="text-xl font-bold mt-6">MCQ 1</h3>
    <p>
      L₁ = &#123; aᵐbⁿ &#125;<br />
      L₂ = &#123; aⁿbⁿ &#125;<br />
      L₃ = &#123; aⁿbⁿcⁿ &#125;
    </p>

    <p className="font-semibold">Correct Answer: C (All three are CFL?) → FALSE</p>

    <p>
      L₃ is not CFL → so option C is incorrect.
    </p>

    {/* MCQ 2 */}
    <h3 className="text-xl font-bold mt-6">MCQ 2</h3>
    <p>
      L = &#123; 0ⁱ1 2ⁱ | i ≥ 0 &#125;
    </p>

    <p className="font-semibold">Correct Answer: B (Deterministic CFL)</p>

    {/* MCQ 3 */}
    <h3 className="text-xl font-bold mt-6">MCQ 3</h3>
    <p>
      L₁ = &#123;0ⁿ1ⁿ&#125;<br />
      L₂ = &#123;wcwʳ&#125;<br />
      L₃ = &#123;wwʳ&#125;
    </p>

    <p className="font-semibold">Correct Answer: C (Only L₁ and L₂ are DCFL)</p>

    {/* MCQ 4 */}
    <h3 className="text-xl font-bold mt-6">MCQ 4</h3>
    <p>
      Grammar generating L = &#123;aⁱbʲ | i ≠ j&#125;
    </p>

    <p className="font-semibold">Correct Answer: D</p>

  </div>
);

export default Home;
