import React from "react";

const Home: React.FC = () => (
  <div className="p-8 space-y-8 rounded-xl shadow-lg mt-20">

    {/* ================= Relationship Between Grammar and Language ================= */}
    <h1 className="text-4xl font-extrabold border-b-2 pb-2">
      Relationship Between Grammar and Language in Theory of Computation
    </h1>
    <p className="text-sm text-gray-500">Last Updated : 30 Jan, 2025</p>

    <p className="leading-relaxed text-lg">
      In the Theory of Computation, a <strong>grammar</strong> is a set of production rules
      that generates a <strong>language</strong>. A language is the set of all strings that
      can be formed using these rules. Understanding this connection is essential in 
      compiler design, automata theory, and parser construction.
    </p>

    {/* ================= Language Generated by a Grammar ================= */}
    <h2 className="text-3xl font-bold mt-8">Language Generated by a Grammar</h2>

    <p className="leading-relaxed">
      For a grammar G, the language L(G) contains all possible strings derivable from G.
      Example grammar:
    </p>

    <p className="bg-gray-400 p-4 rounded-lg shadow-inner text-sm">
      G: S → aSb &#124; ε
    </p>

    <p className="leading-relaxed">
      Using S → ε, we get ε.<br />
      Using S ⇒ aSb ⇒ ab, we get <strong>ab</strong>.<br />
      Using S ⇒ aSb ⇒ aaSbb ⇒ aabb, we get <strong>aabb</strong>.
    </p>

    <p className="leading-relaxed font-semibold">
      Thus, L(G) = &#123; aⁿbⁿ &#124; n ≥ 0 &#125;
    </p>

    <p className="leading-relaxed font-semibold">Key Points:</p>

    <ul className="list-disc ml-6 leading-relaxed">
      <li>L(G) is unique for a given grammar G.</li>
      <li>L(G) contains all strings generated using G.</li>
      <li>No string outside derivations of G can be in L(G).</li>
    </ul>

    {/* ================= Example 1 ================= */}
    <h2 className="text-3xl font-bold mt-8">Example Question 1</h2>
    <p className="leading-relaxed">
      Grammar (GATE-CS-2009):
    </p>

    <p className="bg-gray-400 p-4 rounded-lg shadow-inner text-sm">
      S → aSa &#124; bSb &#124; a &#124; b
    </p>

    <p className="leading-relaxed">
      Generated strings include: a, b, aba, bab, aaa, bbb, ababa…
    </p>

    <p className="leading-relaxed font-semibold">
      Correct answer: (B) All odd-length palindromes
    </p>

    {/* ================= Example 2 ================= */}
    <h2 className="text-3xl font-bold mt-8">Example Question 2</h2>

    <p className="leading-relaxed">
      Consider the grammars G₁ and G₂ (GATE-CS-2016).  
    </p>

    <p className="leading-relaxed font-semibold">Language of G₁:</p>

    <p className="bg-gray-400 p-4 rounded-lg shadow-inner text-sm">
      L(G₁) = &#123; aᵐbⁿ &#124; m ≥ 0 and n &gt; 0 &#125;
    </p>

    <p className="leading-relaxed font-semibold">Language of G₂:</p>

    <p className="bg-gray-400 p-4 rounded-lg shadow-inner text-sm">
      L(G₂) = &#123; aᵐbⁿ &#124; m &gt; 0 or n &gt; 0 &#125;
    </p>

    {/* ================= Grammar Generating a Language ================= */}
    <h2 className="text-3xl font-bold mt-8">Grammar Generating a Given Language</h2>

    <p className="leading-relaxed">
      Given a language L, the grammar G must produce all strings in L and only those strings.
      Example language:
    </p>

    <p className="bg-gray-400 p-4 rounded-lg shadow-inner text-sm">
      L = &#123; aⁿbⁿ &#124; n ≥ 0 &#125;
    </p>

    <p className="leading-relaxed">
      A grammar that generates L:
    </p>

    <p className="bg-gray-400 p-4 rounded-lg shadow-inner text-sm">
      S → aSb &#124; ε
    </p>

    <p className="leading-relaxed font-semibold">Key Points:</p>

    <ul className="list-disc ml-6 leading-relaxed">
      <li>More than one grammar can generate the same language.</li>
      <li>Grammar must produce all strings in the language.</li>
      <li>Grammar must not produce any string outside the language.</li>
    </ul>

    {/* ================= Example 3 ================= */}
    <h2 className="text-3xl font-bold mt-8">Example Question 3</h2>

    <p className="leading-relaxed">
      Find the grammar generating L = &#123; aⁱbʲ &#124; i ≠ j &#125; (GATE-CS-2006)
    </p>

    <p className="leading-relaxed">
      The strings in this language include:
    </p>

    <p className="bg-gray-400 p-4 rounded-lg shadow-inner text-sm">
      &#123; a, b, aa, bb, aaa, bbb, aab, abb, … &#125;
    </p>

    <p className="leading-relaxed">
      Options (A), (B), and (C) all generate the string <strong>ab</strong>,  
      but L does <strong>not</strong> contain ab when i = j = 1.
    </p>

    <p className="leading-relaxed font-semibold">
      Therefore, the correct grammar is: <br />
      <strong>(D)</strong>
    </p>

  </div>
);

export default Home;
