import React from 'react';

const Home: React.FC = () => (
  <div className="p-8 space-y-8 rounded-xl shadow-lg mt-20">

    {/* ================= Turing Machine in TOC ================= */}
    <h1 className="text-4xl font-extrabold border-b-2 pb-2">
      Turing Machine in Theory of Computation
    </h1>
    <p className="text-sm text-gray-500">Last Updated : 05 Feb, 2025</p>

    {/* Introduction */}
    <p className="text-lg leading-relaxed">
      Turing Machines (TM) are abstract computational devices used in the Theory of Computation (TOC) 
      to study the limits of what can be computed. Invented by Alan Turing in 1936, TMs can accept 
      Recursive Enumerable Languages (generated by Type-0 Grammar). Despite their simplicity, they are 
      as powerful as modern computers with infinite memory.
    </p>

    {/* Components */}
    <h2 className="text-3xl font-bold mt-8">Components of a Turing Machine</h2>
    <ul className="list-disc ml-6 leading-relaxed">
      <li>Infinite tape divided into cells, each containing a symbol from the tape alphabet or blank (B)</li>
      <li>Read/write head that moves left or right on the tape</li>
      <li>Finite set of states (Q)</li>
      <li>Input alphabet (Σ)</li>
      <li>Tape alphabet (Γ) including Σ and special symbols</li>
      <li>Transition function (δ)</li>
      <li>Start state (q₀)</li>
      <li>Blank symbol (B)</li>
      <li>Set of final/accepting states (F)</li>
    </ul>

    {/* Why Turing Machines */}
    <h2 className="text-3xl font-bold mt-8">Why Turing Machines?</h2>
    <p className="leading-relaxed">
      Turing Machines provide a clear, mathematical model of computation that is easier to analyze than 
      programming languages. Their infinite memory allows them to solve problems that finite machines cannot.
      They are widely used to study the limits of computation, analyze algorithms, and determine 
      which problems are computable.
    </p>

    {/* TM Formal Definition */}
    <h2 className="text-3xl font-bold mt-8">Formal Definition</h2>
    <p className="leading-relaxed">
      A Turing Machine is defined as a 7-tuple:
    </p>
    <ul className="list-disc ml-6 leading-relaxed">
      <li>Q = finite set of states</li>
      <li>Σ = input alphabet</li>
      <li>Γ = tape alphabet (Σ ⊆ Γ)</li>
      <li>δ = transition function (Q × Γ → Q × Γ × {"L, R"})</li>
      <li>q₀ ∈ Q = start state</li>
      <li>B ∈ Γ = blank symbol</li>
      <li>F ⊆ Q = set of accept/final states</li>
    </ul>

    {/* Example TM */}
    <h2 className="text-3xl font-bold mt-8">Example: TM for L = {'{0ⁿ1ⁿ | n ≥ 1}'}</h2>
    <p className="leading-relaxed">
      This TM accepts strings with equal number of 0's followed by 1's.
    </p>
    <ul className="list-disc ml-6 leading-relaxed">
      <li>Q = {'{q₀, q₁, q₂, q₃}'} (q₀ = initial state)</li>
      <li>Tape alphabet = {'{0,1,X,Y,B}'} (X,Y mark processed symbols)</li>
      <li>Input alphabet Σ = {'{0,1}'}</li>
      <li>F = {'{q₃}'} (final state)</li>
    </ul>

    <h3 className="text-2xl font-semibold mt-4">Transition Table</h3>
    <p className="leading-relaxed">
      Example transitions:<br/>
      δ(q₀, 0) = (q₁, X, R) <br/>
      δ(q₁, 0) = (q₁, 0, R) <br/>
      δ(q₁, 1) = (q₂, Y, L) <br/>
      δ(q₂, 0) = (q₂, 0, L) <br/>
      δ(q₂, X) = (q₀, X, R) <br/>
      δ(q₀, Y) = (q₃, Y, R) (accept)
    </p>

    {/* Working Example */}
    <h2 className="text-3xl font-bold mt-8">Working Example</h2>
    <p className="leading-relaxed">
      Input: 0011
    </p>
    <ol className="list-decimal ml-6 leading-relaxed">
      <li>δ(q₀, 0) → (q₁, X, R): replace 0 by X, move right, change state to q₁.</li>
      <li>δ(q₁, 0) → (q₁, 0, R): move right, stay in q₁.</li>
      <li>δ(q₁, 1) → (q₂, Y, L): replace 1 by Y, move left, go to q₂.</li>
      <li>δ(q₂, 0) → (q₂, 0, L): move left, stay in q₂.</li>
      <li>δ(q₂, X) → (q₀, X, R): move right, back to q₀.</li>
      <li>Continue until all 0's and 1's processed, reach q₃ and halt. String accepted.</li>
    </ol>

    {/* Notes */}
    <h2 className="text-3xl font-bold mt-8">Notes on Turing Machines</h2>
    <ul className="list-disc ml-6 leading-relaxed">
      <li>Non-deterministic TMs allow multiple moves for the same state and symbol but are equivalent in power to deterministic TMs.</li>
      <li>Multi-tape TMs can be simulated by single-tape TMs without additional computational power.</li>
      <li>TM is the most general abstract computational model for solving problems and studying decidability.</li>
    </ul>

    {/* Sample Question */}
    <h2 className="text-3xl font-bold mt-8">Sample Question</h2>
    <p className="leading-relaxed">
      A single-tape TM M has states q₀ (start) and q₁, input alphabet {"0,1"}, tape alphabet {"0,1,B"}. 
      Using its transition function, determine which strings it halts on.
    </p>
    <p className="leading-relaxed">
      Solution: By tracing δ transitions for strings ending with 0 or 1, it is seen that the TM does 
      not halt for strings like "1" or "0", but halts for NULL string. Therefore, option (A) is correct.
    </p>

  </div>
);

export default Home;
