import React from 'react';

const Home: React.FC = () => (
  <div className="p-8 space-y-8 rounded-xl shadow-lg mt-20">

    {/* ================= Process Table & PCB ================= */}
    <h1 className="text-4xl font-extrabold border-b-2 pb-2">
      Process Table and Process Control Block (PCB)
    </h1>
    <p className="text-sm text-gray-500">Last Updated : 19 Sep, 2025</p>

    {/* Intro Paragraph */}
    <p className="text-lg leading-relaxed">
      A <strong>Process Control Block (PCB)</strong> is a crucial data structure used by the 
      operating system to store all information required to manage and execute a process. 
      Every active process has its own PCB, and each process is assigned a unique 
      <strong> Process ID (PID)</strong> for identification.
    </p>

    <p className="leading-relaxed">
      The PCB contains essential details such as process state, program counter, register values, 
      CPU scheduling data, open files, memory limits, and other context information. Whenever a 
      process changes state, the OS updates the PCB accordingly.
    </p>

    <p className="leading-relaxed">
      All PCBs are stored collectively in a data structure called the 
      <strong> Process Table</strong>, which helps the OS keep track of all active processes.
    </p>

    {/* Structure Section */}
    <h2 className="text-3xl font-bold mt-8">Structure of the Process Control Block (PCB)</h2>
    <p className="leading-relaxed">
      The PCB contains multiple fields required for process execution and context switching. 
      These fields allow the OS to pause and resume processes efficiently.
    </p>

    <ul className="list-disc ml-6 leading-relaxed">
      <li>
        <strong>Pointer</strong>: Used during context switching to save and restore the current 
        stack pointer and execution point.
      </li>
      <li>
        <strong>Process State</strong>: Indicates whether the process is running, ready, waiting, 
        or terminated.
      </li>
      <li>
        <strong>Process Number (PID)</strong>: Unique ID assigned to each process.
      </li>
      <li>
        <strong>Program Counter</strong>: Stores the address of the next instruction to execute.
      </li>
      <li>
        <strong>CPU Registers</strong>: Register values are stored when a process is swapped out 
        and restored when it resumes execution.
      </li>
      <li>
        <strong>Memory Limits</strong>: Includes information such as page tables or segment tables 
        used for memory management.
      </li>
      <li>
        <strong>List of Open Files</strong>: Keeps track of all files currently opened by the process.
      </li>
    </ul>

    <p className="leading-relaxed">
      PCBs are stored in protected memory areas, often located at the beginning of the kernel stack 
      of each process, ensuring they remain secure from user-level access.
    </p>

    {/* Process Table Section */}
    <h2 className="text-3xl font-bold mt-8">Process Table</h2>
    <p className="leading-relaxed">
      The <strong>Process Table</strong> is a system-wide data structure that stores an entry for 
      every active process. Each entry typically contains a PID and a pointer to that process’s PCB.
    </p>

    <p className="leading-relaxed">
      While some operating systems also store quick-access information such as process state or 
      parent PID directly in the table, the main and detailed information is always kept in the PCB.
    </p>

    {/* Roles Section */}
    <h2 className="text-3xl font-bold mt-8">Roles of the Process Table & PCB</h2>
    <ul className="list-disc ml-6 leading-relaxed">
      <li>
        <strong>Helps in Scheduling</strong>: Stores priority, CPU burst time, and arrival time.
      </li>
      <li>
        <strong>Facilitates Context Switching</strong>: Maintains CPU registers, program counter, 
        and stack pointer.
      </li>
      <li>
        <strong>Interrupt Handling</strong>: Contains information about interrupts generated by 
        the process.
      </li>
      <li>
        <strong>IPC Support</strong>: Stores data for shared memory, pipes, and message queues.
      </li>
      <li>
        <strong>Resource Allocation</strong>: Tracks allocated memory, I/O devices, and open files.
      </li>
      <li>
        <strong>Synchronization & Deadlock Handling</strong>: Maintains lock and resource-request data.
      </li>
      <li>
        <strong>Security and Access Control</strong>: Includes user ID, group ID, and permissions.
      </li>
      <li>
        <strong>Debugging and Monitoring</strong>: Used by tools like <em>ps</em> and <em>top</em> to 
        display process details.
      </li>
      <li>
        <strong>Virtual Memory Management</strong>: Contains page tables, page fault info, and 
        mapping structures.
      </li>
      <li>
        <strong>Real-Time System Support</strong>: Stores deadlines, priorities, and timing 
        constraints for time-critical tasks.
      </li>
    </ul>

    <p className="leading-relaxed">
      Together, the Process Table and PCB form the core data management system that allows the OS 
      to track, schedule, and control processes efficiently.
    </p>

  </div>
);

export default Home;
