import React from "react";

const SpoolingTheory: React.FC = () => (
  <div className="p-8 space-y-8 rounded-xl shadow-lg mt-20">

    {/* ================= Spooling ================= */}
    <h1 className="text-4xl font-extrabold border-b-2 pb-2">
      Spooling in Operating Systems
    </h1>
    <p className="text-sm text-gray-500">Last Updated : 25 Oct, 2025</p>

    <p className="leading-relaxed text-lg">
      SPOOL stands for <strong>Simultaneous Peripheral Operations On-Line</strong>. 
      It is a buffering technique used to manage input/output (I/O) operations efficiently by temporarily holding data in memory or on disk until the device is ready to process it.
    </p>

    {/* Example */}
    <h2 className="text-3xl font-bold mt-6">Example</h2>
    <p>
      When multiple documents are sent to a printer, the OS stores them in a <strong>spool</strong> (special memory or disk area). 
      The printer retrieves documents one by one, while the user continues other tasks.
    </p>

    {/* Need for Spooling */}
    <h2 className="text-3xl font-bold mt-6">Need for Spooling</h2>
    <p>
      Peripheral devices like printers and keyboards are slower than CPU and RAM, causing potential bottlenecks. Spooling helps by:
    </p>
    <ul className="list-disc ml-6 leading-relaxed">
      <li>Collecting data or instructions from multiple sources.</li>
      <li>Storing them temporarily in a queue.</li>
      <li>Processing them in <strong>FIFO (First-In, First-Out)</strong> order.</li>
    </ul>
    <p>
      This ensures the CPU is never idle waiting for slow I/O operations and can continue executing other processes.
    </p>

    {/* Working of Spooling */}
    <h2 className="text-3xl font-bold mt-6">Working of Spooling</h2>
    <ol className="list-decimal ml-6 leading-relaxed">
      <li>Data is generated by a program or user and sent to an I/O device.</li>
      <li>Data is stored in a <strong>spool area</strong> (temporary storage on disk or memory).</li>
      <li>The device retrieves the data from the spool whenever it becomes available.</li>
      <li>The OS maintains a spool queue ensuring I/O requests are processed in order.</li>
    </ol>

    {/* Applications */}
    <h2 className="text-3xl font-bold mt-6">Applications of Spooling</h2>
    <ul className="list-disc ml-6 leading-relaxed">
      <li>
        <strong>I/O Devices:</strong> Printers, keyboards, and mice use spooling to buffer inputs or print jobs.
      </li>
      <li>
        <strong>Batch Processing Systems:</strong> Jobs are queued in the spool area until resources are available.
      </li>
      <li>
        <strong>Overlapping I/O and Processing:</strong> While one job is performing I/O, the CPU can execute other jobs.
      </li>
      <li>
        <strong>Email Systems:</strong> Outgoing emails are temporarily stored in a spool area before delivery.
      </li>
      <li>
        <strong>Banner Page Generation:</strong> Special pages printed between documents in shared printer environments.
      </li>
    </ul>

    {/* Example Scenario */}
    <h2 className="text-3xl font-bold mt-6">Example Scenario</h2>
    <p>
      In a busy office printer environment, all print jobs are stored in the spool area. The printer fetches one document at a time while other employees continue working. 
      Spooling acts as a bridge between fast CPU processes and slower peripherals.
    </p>

    {/* Advantages */}
    <h2 className="text-3xl font-bold mt-6">Advantages of Spooling</h2>
    <ul className="list-disc ml-6 leading-relaxed">
      <li>Efficient CPU utilization without waiting for I/O operations.</li>
      <li>Improved system performance through overlapping computation and I/O.</li>
      <li>Better resource sharing for multiple processes using the same device.</li>
      <li>Orderly execution of jobs (FIFO).</li>
      <li>Reduced idle time of peripherals like printers and disks.</li>
    </ul>

    {/* Disadvantages */}
    <h2 className="text-3xl font-bold mt-6">Disadvantages of Spooling</h2>
    <ul className="list-disc ml-6 leading-relaxed">
      <li>Requires secondary storage for temporary data.</li>
      <li>Managing large spool queues can increase system overhead.</li>
      <li>Smaller jobs may experience delays if large jobs are queued first.</li>
    </ul>
  </div>
);

export default SpoolingTheory;
