import React from "react";

const ObjectCodeCompiler: React.FC = () => (
  <div className="p-8 space-y-8 rounded-xl shadow-lg mt-20">

    <h1 className="text-4xl font-extrabold border-b-2 pb-2">
      Introduction of Object Code in Compiler Design
    </h1>
    <p className="text-sm text-gray-500">Last Updated : 27 May, 2025</p>

    <p className="leading-relaxed">
      Assume you have a C program. You provide it to the compiler, which produces assembly code. The assembler then converts this assembly code into <strong>object code</strong>.
    </p>

    <h2 className="text-3xl font-bold mt-8">Object Code</h2>
    <p className="leading-relaxed">
      Object code is an intermediate, machine-readable representation generated by the compiler from the source code. It is usually not directly executable and often needs to be linked with other object files to produce the final executable program.
    </p>

    <h3 className="text-2xl font-bold mt-4">Steps Involved in Compilation</h3>
    <ul className="list-disc ml-6 leading-relaxed">
      <li><strong>Source Code:</strong> Written in a high-level programming language (C, Java, Python, etc.).</li>
      <li><strong>Lexical Analysis:</strong> The compiler breaks the source code into tokens (keywords, identifiers, operators, literals).</li>
      <li><strong>Syntax & Semantic Analysis:</strong> Checks grammar and logic correctness and builds the symbol table.</li>
      <li><strong>Intermediate Code Generation:</strong> Produces machine-independent intermediate code for further analysis or optimization.</li>
      <li><strong>Code Generation (Object Code):</strong> Converts intermediate code into object code, machine-level instructions specific to the target architecture.</li>
    </ul>

    <h3 className="text-2xl font-bold mt-4">Structure of Object Code</h3>
    <p className="leading-relaxed">
      Object code is a binary file containing machine instructions but is not directly executable. Its main components include:
    </p>
    <ul className="list-disc ml-6 leading-relaxed">
      <li><strong>Header:</strong> Specifies the parts of the object code, such as the text segment, data segment, relocation info, and symbol information.</li>
      <li><strong>Text Segment:</strong> Contains the instructions of the program.</li>
      <li><strong>Data Sections:</strong> Holds initialized and uninitialized data (.data and .bss sections).</li>
      <li><strong>Relocation Information:</strong> Provides address adjustments needed during linking when combining multiple object files.</li>
      <li><strong>Symbol Table:</strong> Keeps track of variables, functions, and other symbols for linking purposes.</li>
      <li><strong>Debugging Information:</strong> Optional data to help debug the program (file names, line numbers, variable names).</li>
    </ul>

    <h3 className="text-2xl font-bold mt-4">Relocation of Addresses</h3>
    <p className="leading-relaxed">
      If a program is loaded into memory at an address other than 0 (e.g., address 1000), all memory addresses in the object code must be adjusted accordingly. This process is called <strong>relocation</strong>.
    </p>

    <h3 className="text-2xl font-bold mt-4">Features of Object Code</h3>
    <ul className="list-disc ml-6 leading-relaxed">
      <li>Machine-readable format</li>
      <li>Architecture-specific</li>
      <li>Can be linked with other object files and libraries</li>
      <li>May contain debugging information</li>
      <li>Includes relocation information for address adjustments</li>
      <li>Optimizable for performance and size</li>
      <li>Can be disassembled to assembly code</li>
    </ul>

    <h3 className="text-2xl font-bold mt-4">Advantages of Object Code</h3>
    <ul className="list-disc ml-6 leading-relaxed">
      <li><strong>Efficiency:</strong> Optimized for target platform, producing faster code.</li>
      <li><strong>Portability:</strong> Can be compiled for different systems sharing the same platform.</li>
      <li><strong>Debugging:</strong> Easier to trace execution at a low-level.</li>
      <li><strong>Protection:</strong> Obfuscation makes reverse engineering harder.</li>
      <li><strong>Security:</strong> Not human-readable, reducing risk of code theft or tampering.</li>
      <li><strong>Interoperability:</strong> Easily linked with other object files for complete executables.</li>
    </ul>

    <h3 className="text-2xl font-bold mt-4">Disadvantages of Object Code</h3>
    <ul className="list-disc ml-6 leading-relaxed">
      <li><strong>Platform-specific:</strong> Cannot run on different architectures without recompilation.</li>
      <li><strong>Limited Readability:</strong> Low-level code is hard for humans to read or maintain.</li>
      <li><strong>Limited Control:</strong> Developers cannot easily optimize the generated code.</li>
      <li><strong>Compatibility Issues:</strong> May conflict with other system components.</li>
      <li><strong>Code Size:</strong> Often larger due to symbol tables and relocation info.</li>
      <li><strong>Licensing:</strong> May have restrictions on use or distribution.</li>
    </ul>

  </div>
);

export default ObjectCodeCompiler;
