import React from 'react';

const Home: React.FC = () => (
  <div className="p-8 space-y-8 rounded-xl shadow-lg mt-20">

    {/* ================= Parsing Introduction ================= */}
    <h1 className="text-4xl font-extrabold border-b-2 pb-2">
      Parsing - Introduction to Parsers
    </h1>
    <p className="text-sm text-gray-500">Last Updated : 23 Jul, 2025</p>

    <p className="text-lg leading-relaxed">
      <strong>Parsing</strong>, also called syntactic analysis, is the process of analyzing a sequence of tokens 
      to determine the grammatical structure of a program. The tokens are generated by a lexical analyzer 
      and organized into a <strong>parse tree</strong> or <strong>syntax tree</strong>.
    </p>

    <p className="leading-relaxed">
      The parse tree represents how tokens fit together according to the language&apos;s syntax. 
      This structure is crucial for understanding program flow and is used in further stages like code 
      generation or execution. Parsing ensures that the token sequence follows the language rules, 
      making the program valid for additional processing.
    </p>

    {/* ================= Role of Parser ================= */}
    <h2 className="text-3xl font-bold mt-8">Role of a Parser</h2>
    <ul className="list-disc ml-6 leading-relaxed">
      <li>Performs syntactic and semantic analysis and converts code into an intermediate representation.</li>
      <li>Checks context-free syntax rules and ensures proper structure of code.</li>
      <li>Guides context-sensitive analysis, verifying correct use of variables and expressions.</li>
      <li>Constructs an intermediate representation of code for easier processing.</li>
      <li>Generates meaningful error messages when parsing issues are detected.</li>
      <li>Attempts minor error correction to allow parsing to continue.</li>
    </ul>

    {/* ================= Types of Parsing ================= */}
    <h2 className="text-3xl font-bold mt-8">Types of Parsing</h2>
    <p className="leading-relaxed">
      Parsing is divided into two main types:
    </p>
    <ul className="list-disc ml-6 leading-relaxed">
      <li>Top-down Parsing</li>
      <li>Bottom-up Parsing</li>
    </ul>

    {/* ================= Top-Down Parsing ================= */}
    <h3 className="text-2xl font-semibold mt-6">Top-Down Parsing</h3>
    <p className="leading-relaxed">
      Top-down parsing builds a parse tree from the <strong>start symbol</strong> (root) down to the leaves (terminals). 
      The parser starts with the highest-level rule and recursively expands non-terminals until the input string is matched.
    </p>

    <ul className="list-disc ml-6 leading-relaxed">
      <li><strong>Leftmost Derivation:</strong> Expands the leftmost non-terminal first.</li>
      <li><strong>Also called:</strong> Recursive or predictive parsing, often using recursive functions.</li>
    </ul>

    <h4 className="text-xl font-semibold mt-4">Top-Down Parsing with Backtracking</h4>
    <p className="leading-relaxed">
      The parser tries multiple possibilities and backtracks if a choice fails.
      <strong> Advantage:</strong> Handles grammars with multiple ways to expand non-terminals. 
      <strong> Disadvantage:</strong> Can be slow due to repeated attempts.
    </p>

    <h4 className="text-xl font-semibold mt-4">Top-Down Parsing without Backtracking</h4>
    <p className="leading-relaxed">
      The parser does not backtrack and sticks to its first choice.
      <strong> Advantage:</strong> Faster parsing. 
      <strong> Disadvantage:</strong> Only works for simple grammars.
    </p>

    {/* ================= Bottom-Up Parsing ================= */}
    <h3 className="text-2xl font-semibold mt-6">Bottom-Up Parsing</h3>
    <p className="leading-relaxed">
      Bottom-up parsing builds a parse tree from <strong>leaves</strong> (input symbols) to the <strong>root</strong> (start symbol), 
      reducing the input string step by step using grammar rules.
    </p>

    <ul className="list-disc ml-6 leading-relaxed">
      <li><strong>Rightmost Derivation in Reverse:</strong> Traces the rightmost derivation backwards.</li>
      <li><strong>Shift-Reduce Parsing:</strong> Moves symbols (shift) and applies rules (reduce) to build the tree.</li>
      <li>Efficient for complex grammars, commonly used in compilers.</li>
    </ul>

    <h4 className="text-xl font-semibold mt-4">Types of Bottom-Up Parsers</h4>
    <ul className="list-disc ml-6 leading-relaxed">
      <li><strong>LR Parsing / Shift-Reduce Parsing:</strong> Includes LR(0), SLR(1), LALR, CLR.</li>
      <li><strong>Operator Precedence Parsing:</strong> Works with operator grammars, without null productions or adjacent non-terminals.</li>
    </ul>

    {/* ================= Difference Table ================= */}
    <h3 className="text-2xl font-semibold mt-6">Difference Between Top-Down and Bottom-Up Parsing</h3>
    <table className="table-auto border-collapse border border-gray-300 w-full text-left mt-2">
      <thead>
        <tr>
          <th className="border border-gray-300 px-2 py-1">Feature</th>
          <th className="border border-gray-300 px-2 py-1">Top-Down Parsing</th>
          <th className="border border-gray-300 px-2 py-1">Bottom-Up Parsing</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td className="border border-gray-300 px-2 py-1">Direction</td>
          <td className="border border-gray-300 px-2 py-1">Builds tree from root to leaves.</td>
          <td className="border border-gray-300 px-2 py-1">Builds tree from leaves to root.</td>
        </tr>
        <tr>
          <td className="border border-gray-300 px-2 py-1">Derivation</td>
          <td className="border border-gray-300 px-2 py-1">Uses leftmost derivation.</td>
          <td className="border border-gray-300 px-2 py-1">Uses rightmost derivation in reverse.</td>
        </tr>
        <tr>
          <td className="border border-gray-300 px-2 py-1">Efficiency</td>
          <td className="border border-gray-300 px-2 py-1">Can be slower, especially with backtracking.</td>
          <td className="border border-gray-300 px-2 py-1">More efficient for complex grammars.</td>
        </tr>
        <tr>
          <td className="border border-gray-300 px-2 py-1">Example Parsers</td>
          <td className="border border-gray-300 px-2 py-1">Recursive descent, LL parser.</td>
          <td className="border border-gray-300 px-2 py-1">Shift-reduce, LR parser.</td>
        </tr>
      </tbody>
    </table>

  </div>
);

export default Home;
