import React from 'react';

const Home: React.FC = () => (
  <div className="p-8 space-y-8 rounded-xl shadow-lg mt-20">

    {/* ================= Hardwired and Micro-programmed Control Unit ================= */}
    <h1 className="text-4xl font-extrabold border-b-2 pb-2">
      Hardwired and Micro-programmed Control Unit
    </h1>
    <p className="text-sm text-gray-500">Last Updated : 09 Sep, 2025</p>

    {/* Intro Paragraph */}
    <p className="text-lg leading-relaxed">
      The Control Unit (CU) of a CPU directs operations and manages the flow of instructions and data inside the processor. It ensures that tasks are executed in the correct sequence. There are two main types of control units: Hardwired and Micro-programmed.
    </p>
    <ul className="list-disc ml-6 leading-relaxed">
      <li><strong>Hardwired Control Unit:</strong> Fast but less flexible because it relies on fixed logic circuits.</li>
      <li><strong>Microprogrammed Control Unit:</strong> Flexible but slower because it uses microcode stored in memory.</li>
    </ul>

    {/* Hardwired Control Unit */}
    <h2 className="text-3xl font-bold mt-6">Hardwired Control Unit</h2>
    <p className="text-lg leading-relaxed">
      Hardwired control uses fixed logic circuits and can be viewed as a state machine. The machine transitions from one state to another in each clock cycle based on instruction register contents, condition codes, and external inputs. The outputs of this state machine are the control signals. Because the control sequence is determined by wiring, this method is called “hardwired.”
    </p>
    <ul className="list-disc ml-6 leading-relaxed">
      <li>Control signals are generated directly from Boolean logic expressions.</li>
      <li>Hardwired control is faster than microprogrammed control.</li>
      <li>RISC architectures are commonly based on hardwired control units.</li>
    </ul>

    {/* Micro-programmed Control Unit */}
    <h2 className="text-3xl font-bold mt-6">Micro-programmed Control Unit</h2>
    <p className="text-lg leading-relaxed">
      In a micro-programmed control unit, control signals for CPU operations are stored in special memory as control words. These signals are generated by executing a program of microinstructions similar to machine language programs. Fetching microinstructions from memory makes microprogrammed control slower than hardwired control.
    </p>

    {/* Important Terms */}
    <h3 className="text-2xl font-bold mt-4">Some Important Terms</h3>
    <ul className="list-disc ml-6 leading-relaxed">
      <li><strong>Control Word:</strong> A word where each bit represents a specific control signal.</li>
      <li><strong>Micro-routine:</strong> Sequence of control words corresponding to a machine instruction.</li>
      <li><strong>Micro-instruction:</strong> Individual control words in a micro-routine.</li>
      <li><strong>Micro-program:</strong> Sequence of micro-instructions stored in Control Memory (ROM or RAM).</li>
      <li><strong>Control Store:</strong> Memory holding micro-routines for all instructions in the instruction set.</li>
    </ul>

    {/* Types of Micro-programmed Control Unit */}
    <h3 className="text-2xl font-bold mt-4">Types of Micro-programmed Control Unit</h3>
    <p className="text-lg leading-relaxed">
      Based on the type of control word in memory, micro-programmed control units are classified into:
    </p>

    <h4 className="text-xl font-semibold mt-2">1. Horizontal Micro-programmed Control Unit</h4>
    <ul className="list-disc ml-6 leading-relaxed">
      <li>Control signals are represented in decoded binary format (1 bit per control signal).</li>
      <li>Supports longer control words and high degree of parallelism.</li>
      <li>Faster than vertical microprogrammed control since no extra decoders are needed.</li>
      <li>Used in parallel processing applications.</li>
      <li>More flexible than vertical microprogrammed control.</li>
    </ul>

    <h4 className="text-xl font-semibold mt-2">2. Vertical Micro-programmed Control Unit</h4>
    <ul className="list-disc ml-6 leading-relaxed">
      <li>Control signals are represented in encoded binary format; for N control signals, log₂(N) bits are needed.</li>
      <li>Supports shorter control words and easier addition of new control signals.</li>
      <li>Low degree of parallelism (0 or 1 signal enabled at a time).</li>
      <li>Requires decoders to generate control signals, making it slower than horizontal microprogrammed control.</li>
      <li>Less flexible than horizontal but more flexible than hardwired control.</li>
    </ul>

  </div>
);

export default Home;
