import React from 'react';

const Home: React.FC = () => (
  <div className="p-8 space-y-8 rounded-xl shadow-lg mt-20">

    {/* ================= Segmentation ================= */}
    <h1 className="text-4xl font-extrabold border-b-2 pb-2">
      Segmentation in Operating System
    </h1>
    <p className="text-sm text-gray-500">Last Updated : 09 Sep, 2025</p>

    {/* Intro Paragraph */}
    <p className="text-lg leading-relaxed">
      Segmentation is a memory management technique where a process is divided into variable-sized 
      chunks called <strong>segments</strong>. Unlike paging, segmentation matches the user’s 
      logical view of a program (functions, arrays, modules) to physical memory.
    </p>

    <p className="leading-relaxed">
      It reflects the user’s view of memory rather than the computer’s physical organization, 
      making it easier to manage and protect processes.
    </p>

    {/* Key Features */}
    <h2 className="text-3xl font-bold mt-8">Key Features of Segmentation</h2>
    <ul className="list-disc ml-6 leading-relaxed">
      <li><strong>Variable-sized divisions:</strong> Segments can have different lengths, depending on the program’s requirements.</li>
      <li><strong>Logical division of memory:</strong> Segments represent meaningful units like code, stack, data, or modules.</li>
      <li><strong>Two-part address:</strong> A logical address consists of Segment number (s) and Offset (d). Logical Address = ⟨Segment number, Offset⟩</li>
      <li><strong>Protection and sharing:</strong> Different segments can have access rights (read, write, execute) and can be shared among processes.</li>
      <li><strong>No internal fragmentation:</strong> Since segments are not fixed in size.</li>
      <li><strong>External fragmentation:</strong> Can occur when free memory is divided into small scattered blocks.</li>
    </ul>

    {/* Types of Segmentation */}
    <h2 className="text-3xl font-bold mt-8">Types of Segmentation in Operating Systems</h2>
    <ul className="list-disc ml-6 leading-relaxed">
      <li><strong>Virtual Memory Segmentation:</strong> Segments may or may not be loaded at runtime.</li>
      <li><strong>Simple Segmentation:</strong> All segments of a process are loaded at runtime, not necessarily contiguously.</li>
    </ul>

    <p className="leading-relaxed">
      There is no simple relationship between logical addresses and physical addresses. A <strong>Segment Table</strong> stores the mapping information.
    </p>

    {/* Segment Table */}
    <h2 className="text-3xl font-bold mt-8">What is Segment Table?</h2>
    <p className="leading-relaxed">
      The Segment Table maps a two-dimensional logical address into a one-dimensional physical address. Each table entry has:
    </p>
    <ul className="list-disc ml-6 leading-relaxed">
      <li><strong>Base Address:</strong> Starting physical address of the segment.</li>
      <li><strong>Segment Limit:</strong> Length of the segment (also called segment offset).</li>
    </ul>

    {/* Translation */}
    <h2 className="text-3xl font-bold mt-8">Translation of Logical Address</h2>
    <p className="leading-relaxed">
      The address generated by the CPU is divided into:
    </p>
    <ul className="list-disc ml-6 leading-relaxed">
      <li><strong>Segment number (s):</strong> Number of bits required to represent the segment.</li>
      <li><strong>Segment offset (d):</strong> Number of bits to represent the position of data within a segment.</li>
    </ul>

    {/* Advantages */}
    <h2 className="text-3xl font-bold mt-8">Advantages of Segmentation</h2>
    <ul className="list-disc ml-6 leading-relaxed">
      <li>Reduced Internal Fragmentation: Segments are sized per program needs.</li>
      <li>Smaller Segment Table: Less memory required than page tables.</li>
      <li>Better CPU Utilization: Entire modules are loaded at once.</li>
      <li>Closer to User’s View: Programs divided into logical modules.</li>
      <li>User-Controlled Size: Segment size is defined by user.</li>
      <li>Security & Separation: Segments isolate sensitive data and operations.</li>
    </ul>

    {/* Disadvantages */}
    <h2 className="text-3xl font-bold mt-8">Disadvantages of Segmentation</h2>
    <ul className="list-disc ml-6 leading-relaxed">
      <li>External Fragmentation: Free memory gets scattered.</li>
      <li>Overhead: Segment table maintenance requires extra memory.</li>
      <li>Slower Access: Two memory lookups increase access time.</li>
      <li>Complexity: Managing variable-sized segments is harder than paging.</li>
      <li>Segmentation Faults: Accessing memory outside a segment causes errors.</li>
    </ul>

  </div>
);

export default Home;
