import React from 'react';

const Home: React.FC = () => (
  <div className="p-8 space-y-8 rounded-xl shadow-lg mt-20">

    {/* ================= Introduction to Control Unit and its Design ================= */}
    <h1 className="text-4xl font-extrabold border-b-2 pb-2">
      Introduction to Control Unit and its Design
    </h1>
    <p className="text-sm text-gray-500">Last Updated : 14 Oct, 2025</p>

    {/* Intro Paragraph */}
    <p className="text-lg leading-relaxed">
      The control unit (CU) is a crucial part of the CPU that directs processor operations. It fetches instructions from memory, decodes them, and generates control signals to manage the ALU, memory, and I/O devices. Its main role is coordinating instruction execution and ensuring smooth operation of all CPU components.
    </p>

    {/* Functions of CU */}
    <h2 className="text-3xl font-bold mt-6">Functions of the Control Unit</h2>
    <ul className="list-disc ml-6 leading-relaxed">
      <li>Coordinates data movement within the CPU</li>
      <li>Interprets instructions and generates control signals</li>
      <li>Controls the flow of data inside the processor</li>
      <li>Manages execution units such as ALU, registers, and buffers</li>
      <li>Handles instruction fetch, decode, execute, and store cycles</li>
    </ul>

    {/* Types of Control Unit */}
    <h2 className="text-3xl font-bold mt-6">Types of Control Unit</h2>
    <p className="text-lg leading-relaxed">
      There are two main types of control units:
    </p>
    <ul className="list-disc ml-6 leading-relaxed">
      <li><strong>Hardwired Control Unit:</strong> Uses fixed logic circuits to generate control signals. Fast but less flexible.</li>
      <li><strong>Microprogrammed Control Unit:</strong> Uses microinstructions stored in control memory to produce control signals. More flexible but slower.</li>
    </ul>

    {/* Hardwired CU */}
    <h3 className="text-2xl font-semibold mt-4">Hardwired Control Unit</h3>
    <p className="text-lg leading-relaxed">
      In hardwired CU, control signals are generated by fixed logic based on the instruction opcode. A decoder activates a control signal matrix, producing execution signals. Timing signals from a quartz oscillator regulate the instruction cycle, while external interrupts and flags modify state transitions.
    </p>

    {/* Microprogrammed CU */}
    <h3 className="text-2xl font-semibold mt-4">Microprogrammed Control Unit</h3>
    <p className="text-lg leading-relaxed">
      In microprogrammed CU, the opcode points to a microprogram in the control store. Each microinstruction generates the necessary control signals for execution.
    </p>

    {/* Important Terms */}
    <h3 className="text-2xl font-semibold mt-4">Important Terms</h3>
    <ul className="list-disc ml-6 leading-relaxed">
      <li><strong>Control Word:</strong> A word with individual bits representing control signals</li>
      <li><strong>Micro-routine:</strong> Sequence of control words for a machine instruction</li>
      <li><strong>Micro-instruction:</strong> A single control word in a micro-routine</li>
      <li><strong>Micro-program:</strong> Sequence of microinstructions stored in Control Memory (CM)</li>
      <li><strong>Control Store:</strong> Memory storing all micro-routines for a processor</li>
    </ul>

    {/* Single-Level Control Store */}
    <h3 className="text-2xl font-semibold mt-4">Single-Level Control Store</h3>
    <p className="text-lg leading-relaxed">
      The opcode points to the start address of a microprogram. Each microinstruction contains encoded control signals and the next microinstruction’s address. Conditional addressing uses processor flags to select the next instruction.
    </p>

    {/* Two-Level Control Store */}
    <h3 className="text-2xl font-semibold mt-4">Two-Level Control Store</h3>
    <p className="text-lg leading-relaxed">
      Microinstructions point to nano-instructions containing the actual encoded control signals. This reduces the total control memory size, as shorter microinstructions handle sequencing while nano-instructions generate the control signals. Nano-instructions often use simple 1-bit per signal encoding without further decoding.
    </p>

  </div>
);

export default Home;
