import React from "react";

const WebAssemblyJavaScript: React.FC = () => {
  return (
    <div className="mt-20 space-y-8">

      {/* Title */}
      <h1 className="text-4xl font-extrabold border-b-2 pb-3">
        WebAssembly - JavaScript
      </h1>

      {/* Intro */}
      <p className="leading-relaxed">
        JavaScript has been the primary programming language inside browsers for
        decades. With the introduction of WebAssembly (WASM), developers now
        have another powerful option for running high-performance code inside the
        browser.
      </p>

      <p className="leading-relaxed">
        WebAssembly was not created to replace JavaScript. Instead, it works
        alongside JavaScript and helps solve performance-heavy tasks that are
        difficult to implement efficiently using JavaScript alone.
      </p>

      {/* Examples */}
      <p className="leading-relaxed">Some examples of tasks difficult for JavaScript include:</p>

      <ul className="list-disc ml-6 space-y-1 leading-relaxed">
        <li>Image recognition</li>
        <li>CAD applications</li>
        <li>Live video augmentation</li>
        <li>VR and Augmented Reality</li>
        <li>Music and audio processing</li>
        <li>Scientific simulations and visualization</li>
        <li>Games</li>
        <li>Image / video editing</li>
      </ul>

      <p className="leading-relaxed">
        High-level languages like <b>C</b>, <b>C++</b>, and <b>Rust</b> can now
        compile to WebAssembly, making such complex tasks easier and faster to execute.
      </p>

      {/* Comparison Table */}
      <h2 className="text-2xl font-bold">JavaScript vs WebAssembly</h2>

      <div className="overflow-x-auto">
        <table className="w-full border border-gray-300 text-left">
          <thead className="bg-gray-100">
            <tr>
              <th className="border p-3 font-semibold">Parameters</th>
              <th className="border p-3 font-semibold">JavaScript</th>
              <th className="border p-3 font-semibold">WebAssembly</th>
            </tr>
          </thead>

          <tbody>
            {/* Coding */}
            <tr>
              <td className="border p-3 font-bold">Coding</td>
              <td className="border p-3">
                Easy to write and human readable. Saved as <code>.js</code>.
                Executed inside browsers using the <code>&lt;script&gt;</code> tag.
              </td>
              <td className="border p-3">
                Written in text format as <code>.wat</code> but difficult to write manually.
                Usually generated by compiling high-level languages.  
                Cannot run <code>.wat</code> directly—must be converted to <code>.wasm</code>.
              </td>
            </tr>

            {/* Execution */}
            <tr>
              <td className="border p-3 font-bold">Execution</td>
              <td className="border p-3">
                JavaScript must be downloaded, parsed, compiled, and optimized by the browser.
              </td>
              <td className="border p-3">
                WebAssembly <code>.wasm</code> is already compiled in binary format,
                making execution faster.
              </td>
            </tr>

            {/* Memory */}
            <tr>
              <td className="border p-3 font-bold">Memory Management</td>
              <td className="border p-3">
                JavaScript handles memory automatically using garbage collection.
              </td>
              <td className="border p-3">
                WebAssembly memory is a flat ArrayBuffer managed manually using
                <code> WebAssembly.Memory() </code>.  
                <br/>Notable drawbacks:
                <ul className="list-disc ml-6">
                  <li>Complex calculations take time.</li>
                  <li>No garbage collection → memory cannot be reused automatically.</li>
                </ul>
              </td>
            </tr>

            {/* Load & Performance */}
            <tr>
              <td className="border p-3 font-bold">Load Time & Performance</td>
              <td className="border p-3">
                JavaScript engines are highly optimized; performance is very fast.
              </td>
              <td className="border p-3">
                WebAssembly aims to be faster than JavaScript.  
                <br />WASM files are compact, so loading time is fast.  
                <br />However, languages like Go generate larger .wasm files.  
                <br />WebAssembly performance continues to improve but is not yet superior in all cases.
              </td>
            </tr>

            {/* Debugging */}
            <tr>
              <td className="border p-3 font-bold">Debugging</td>
              <td className="border p-3">
                JavaScript is human-readable and easy to debug using browser developer tools.
              </td>
              <td className="border p-3">
                WebAssembly code is readable in <code>.wat</code> format, but still difficult to debug.  
                Browsers like Firefox show WASM in text format, but breakpoints and debugging tools are still limited.
              </td>
            </tr>

            {/* Browser Support */}
            <tr>
              <td className="border p-3 font-bold">Browser Support</td>
              <td className="border p-3">Works in all browsers.</td>
              <td className="border p-3">Supported by all major browsers.</td>
            </tr>

          </tbody>
        </table>
      </div>
    </div>
  );
};

export default WebAssemblyJavaScript;
