import React from "react";

const WebAssemblyWasm: React.FC = () => {
  return (
    <div className="mt-20 space-y-8">
      {/* Title */}
      <h1 className="text-4xl font-extrabold border-b-2 pb-3">
        WebAssembly - WASM
      </h1>

      {/* Intro */}
      <p className="leading-relaxed">
        WebAssembly, commonly called <b>wasm</b>, is designed to run inside web
        browsers just like JavaScript and is also supported in Node.js. When
        high-level languages like <b>C</b>, <b>C++</b>, or <b>Rust</b> are
        compiled, the output produced is WASM.
      </p>

      {/* C Example */}
      <h2 className="text-2xl font-bold">C Program Example</h2>
      <p className="leading-relaxed">
        Consider the following C program that calculates the factorial of a
        number:
      </p>

      <pre className="bg-gray-100 p-3 rounded-md font-mono text-black">
{`int factorial(int n) {
   if (n == 0) 
      return 1; 
   else 
      return n * factorial(n - 1); 
}`}
      </pre>

      <p className="leading-relaxed">
        You can use tools like <b>WasmExplorer</b> (https://mbebenita.github.io/WasmExplorer/)
        to compile this code into WebAssembly.
      </p>

      {/* WebAssembly Text Representation */}
      <h2 className="text-2xl font-bold">WebAssembly Text Format</h2>
      <p className="leading-relaxed">
        The WebAssembly text format (<code>.wat</code>) for the factorial
        program generated by WasmExplorer looks like this:
      </p>

      <pre className="bg-gray-100 p-3 rounded-md font-mono text-black overflow-x-auto">
{`(module 
   (table 0 anyfunc) 
   (memory $0 1) 
   (export "memory" (memory $0)) 
   (export "factorial" (func $factorial)) 
   (func $factorial (; 0 ;) (param $0 i32) (result i32)
      (local $1 i32) 
      (local $2 i32) 
      (block $label$0 
         (br_if $label$0 
            (i32.eqz (get_local $0))
         )
         (set_local $2 (i32.const 1)) 
         (loop $label$1 
            (set_local $2 
               (i32.mul (get_local $0) (get_local $2))
            ) 
            (set_local $0 
               (tee_local $1 (i32.add (get_local $0) (i32.const -1)))
            ) 
            (br_if $label$1 (get_local $1))
         ) 
         (return (get_local $2))
      ) 
      (i32.const 1)
   )
)`}
      </pre>

      <p className="leading-relaxed">
        Using tools like <b>Wat2Wasm</b>, developers can convert this text format
        into a <code>.wasm</code> binary. In most cases, developers do not write
        WebAssembly manually — it is automatically generated during compilation.
      </p>

      {/* Stack Machine Model */}
      <h2 className="text-2xl font-bold">Stack Machine Model</h2>
      <p className="leading-relaxed">
        WebAssembly uses a <b>stack machine model</b>. Instructions push values
        onto the stack, pop arguments from it, and push the results back.
      </p>

      <p className="leading-relaxed">
        Here is a simple WebAssembly text format example that adds two numbers:
      </p>

      <pre className="bg-gray-100 p-3 rounded-md font-mono text-black">
{`(module
   (func $add (param $a i32) (param $b i32) (result i32) 
      get_local $a 
      get_local $b 
      i32.add
   )
   (export "add" (func $add))
)`}
      </pre>

      <p className="leading-relaxed">
        The <b>$add</b> function takes two parameters <b>$a</b> and <b>$b</b> of
        type <code>i32</code>. The values are retrieved using{" "}
        <code>get_local</code> and added together using <code>i32.add</code>.
      </p>

      {/* Stack Representation */}
      <h3 className="text-xl font-semibold">Stack Representation</h3>
      <ul className="list-disc ml-6 space-y-2 leading-relaxed">
        <li>
          <b>Step 1:</b> <code>get_local $a</code> pushes the first parameter
          onto the stack.
        </li>
        <li>
          <b>Step 2:</b> <code>get_local $b</code> pushes the second parameter
          onto the stack.
        </li>
        <li>
          <b>Step 3:</b> <code>i32.add</code> pops both values, adds them, and
          pushes the result back onto the stack.
        </li>
      </ul>

      <p className="leading-relaxed">
        The final value remaining on the stack becomes the return value of the{" "}
        <b>$add</b> function.
      </p>
    </div>
  );
};

export default WebAssemblyWasm;
